local_repository(
    name = "misc_rules",
    path = "../../../../",
)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_tweag_rules_nixpkgs",
    commit = "40b5a9f23abca57f364c93245c7451206ef1a855",
    remote = "git://github.com/tweag/rules_nixpkgs",
)

load(
    "@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl",
    "nixpkgs_local_repository",
    "nixpkgs_package",
)

nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "@misc_rules//3rdparty:nixpkgs.nix",
)

nixpkgs_package(
    name = "shellcheck",
    repository = "@nixpkgs",
)

register_toolchains(
    "@misc_rules//toolchains:shellcheck_from_nixpkgs",
)
