local_repository(
    name = "misc_rules",
    path = "../../../../",
)

load("@misc_rules//:workspace0.bzl", "workspace0")

workspace0()

load("@misc_rules//:workspace1.bzl", "workspace1")

workspace1()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_package")

nixpkgs_package(
    name = "shellcheck",
    repository = "@nixpkgs",
)

register_toolchains(
    "@misc_rules//toolchains:shellcheck_from_nixpkgs",
)
