#!/usr/bin/env bash

set -e
cd "$(dirname "$0")"

tmp="$(mktemp -d)"

if [[ ! "$tmp" || ! -d "$tmp" ]]; then
  echo "Could not create temp dir"
  exit 1
fi

function cleanup {
  rm -rf "$tmp"
}
trap cleanup EXIT

cat <<EOF > "$tmp"/batman
#!/usr/bin/env bash
echo "EASY_TO_FIND_MESSAGE"
exit 1
EOF
chmod +x "$tmp"/batman

for thing in shellcheck black; do
    THING=$(echo "$thing" | tr '[:lower:]' '[:upper:]')
    echo "> $thing"

    echo "- test 1"
    ./tools/bazel test @shared//:"$thing"_test 2>&1 | grep "${THING}_PATH must be set" > /dev/null || {
	echo "$thing test 1 failed"
	exit 1
    }

    echo "- test 2"
    ./tools/bazel test --test_env "$THING"_PATH="$tmp"/batman @shared//:"$thing"_test 2>&1 | grep "EASY_TO_FIND_MESSAGE" > /dev/null || {
	echo "$thing test 2 failed"
	exit 1
    }
done
