local_repository(
    name = "shared",
    path = "../shared",
)

local_repository(
    name = "misc_rules",
    path = "../../../",
)

register_toolchains(
    "@misc_rules//toolchains/shellcheck:shellcheck_from_shellcheck_path",
    "@misc_rules//toolchains/black:black_from_black_path",
)
