local_repository(
    name = "shared",
    path = "../shared",
)

local_repository(
    name = "misc_rules",
    path = "../../../",
)

load("@misc_rules//:workspace0.bzl", "workspace0")

workspace0()

load("@misc_rules//:workspace1.bzl", "workspace1")

workspace1()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_package")

nixpkgs_package(
    name = "shellcheck",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "yamllint",
    attribute_path = "python36Packages.yamllint",
    repository = "@nixpkgs",
)

register_toolchains(
    "@misc_rules//toolchains:shellcheck_from_nixpkgs",
    "@misc_rules//toolchains:yamllint_from_nixpkgs",
)
