local_repository(
    name = "shared",
    path = "../shared",
)

local_repository(
    name = "misc_rules",
    path = "../../../",
)

load("@misc_rules//:workspace0.bzl", "workspace0")

workspace0()

load("@misc_rules//:workspace1.bzl", "workspace1")

workspace1()